#!/bin/bash
# Define the list of directories
DIRECTORIES=(
    AIRNOW CRIS_CH4 CRIS_NH3 CRIS_PAN GOME2B_NO2 IASI_O3 MEXICO_AQS MLS_O3 MOPITT_CO OMI_NO2 OMI_SO2 SCIAM_NO2 TEMPO_O3 TES_CO TES_NH3 TROPOMI_CH4 TROPOMI_HCHO TROPOMI_O3
    AQSMEX CRIS_CO CRIS_O3 GOME2A_NO2 IASI_CO MAXDOAS_NO2 MLS_HNO3 MODIS_AOD OMI_HCHO OMI_O3 PANDA TEMPO_NO2 TES_CH4 TES_CO2 TES_O3 TROPOMI_CO TROPOMI_NO2 TROPOMI_SO2
)
export DART="${PWD}"
for dir in "${DIRECTORIES[@]}"; do
	if [[ -f ${dir}/work/quickbuild.sh ]]; then
		cd ${dir}/work
		./quickbuild.sh
		cd ${DART}
	fi
done
